name: Build and deploy

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'
      - name: Run build with Gradle Wrapper
        run: ./gradlew clean build -x test
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: built-artifacts
          path: |
            build/libs/*.jar
            Dockerfile
  build-docker-image:
    needs: 'build-gradle-project'
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: built-artifacts
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: registry.digitalocean.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push docker image
        run: |
          docker buildx build --platform linux/amd64 -t registry.digitalocean.com/connect-services/backend-service:${{ github.sha }} --push .
          docker buildx build --platform linux/amd64 -t registry.digitalocean.com/connect-services/backend-service:latest --push .
