name: Build and deploy

on:
  workflow_dispatch:

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'
      - name: Run build with Gradle Wrapper
        run: ./gradlew clean build -x test
      - name: Cache artifact
        id: cache-artifact
        uses: actions/cache@v3
        with:
          path: |
            build/libs
            Dockerfile
          key: ${{ runner.os }}-cache
  build-docker-image:
    needs: 'build-gradle-project'
    runs-on: ubuntu-latest
    steps:
      - name: Restore cached artifact
        id: cache-artifact-restore
        uses: actions/cache/restore@v3
        with:
          path: |
            build/libs
            Dockerfile
          key: ${{ runner.os }}-cache
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: registry.digitalocean.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push docker image
        run: |
          docker buildx build --platform linux/amd64 -t registry.digitalocean.com/connect-services/backend-service:${{ github.sha }} --push .
          docker buildx build --platform linux/amd64 -t registry.digitalocean.com/connect-services/backend-service:latest --push .
